// recipiece/apps/landing/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'recipiece-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="form-container">
  <div class="form">
    <h2>Login</h2>
    <fieldset>
      <label>
        Username or Email
        <input [(ngModel)]="username" name="rcp-username" type="text" />
      </label>
      <label>
        Password
        <input [(ngModel)]="password" type="password" name="rcp-password" />
      </label>
      <label class="label-inline">
        <input [(ngModel)]="remember" type="checkbox" name="rcp-remember" />
        Remember
      </label>
    </fieldset>
    <div class="button-container">
      <button [disabled]="!valid" class="button" type="button" (click)="loginUser()">Log In</button>
      <button routerLink="../create-account" class="button button-outline" type="button">Create Account</button>
    </div>
    <a routerLink="../forgot-password" class="button button-clear forgot-password-button">Forgot Password</a>
    <recipiece-loading-spinner [loading]="loading"></recipiece-loading-spinner>
  </div>
</div>

// login/src/pages/login/login.tsx
import { login } from '@recipiece/module-common';
import React, { useCallback, useReducer, VFC } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { loginReducer } from './login.reducer';
import './login.scss';
import { DEFAULT_LOGIN_STATE } from './login.state';

export const LoginComponent: VFC = () => {
  const [state, dispatch] = useReducer(loginReducer, DEFAULT_LOGIN_STATE);
  const navigate = useNavigate();

  const handleSubmit = useCallback(
    async (e) => {
      e.preventDefault();
      try {
        await login(state.username, state.password);
        navigate('/dashboard');
      } catch (e) {}
    },
    [state.username, state.password]
  );

  const setUsername = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    dispatch({
      type: 'SET_USERNAME',
      payload: e.target.value,
    });
  }, []);

  return (
    <div className="container">
      <div className="form-container form-group">
        <form onSubmit={handleSubmit}>
          <h3>Log In</h3>
          <label className="form-label">
            Email
            <input className="form-input" type="text" name="username" onChange={setUsername} />
          </label>
          <label className="form-label">
            Password
            <input className="form-input" type="password" name="password" />
          </label>
          <label className="form-switch">
            <input name="remember" type="checkbox" />
            Remember Me
          </label>
          <div className="actions-container">
            <div className="button-container">
              <button type="submit" className="btn btn-primary">
                Log In
              </button>
              <Link to="/landing/create-account">
                <button type="button" className="btn">
                  Create Account
                </button>
              </Link>
            </div>
            <Link to="/landing/forgot-password">
              <button type="button" className="btn btn-link">
                Forgot Password
              </button>
            </Link>
          </div>
        </form>
      </div>
    </div>
  );
};
