// login/src/pages/create-account/create-account.tsx
import React, { useCallback, VFC } from "react";
import { Link, useNavigate } from "react-router-dom";

export const CreateAccountComponent: VFC = () => {
  const navigate = useNavigate();

  const handleSubmit = useCallback((e: React.FormEvent) => {
    e.preventDefault();
    navigate("/landing/confirm-account");
  }, []);

  return (
    <div className="container">
      <div className="form-container form-group">
        <h3>Create an Account</h3>
        <form onSubmit={handleSubmit}>
          <label className="form-label">
            Email
            <input name="email" className="form-input" type="text" />
          </label>
          <label className="form-label">
            Username
            <input name="username" className="form-input" type="text" />
          </label>
          <label className="form-label">
            Password
            <input name="password" className="form-input" type="password" />
          </label>
          <label className="form-label">
            Confirm Password
            <input
              name="confirm-password"
              className="form-input"
              type="password"
            />
          </label>
          <div className="actions-container">
            <div className="button-container">
              <button type="submit" className="btn btn-primary">
                Create Account
              </button>
            </div>
            <Link to="/landing/login">
              <button type="button" className="btn btn-link">
                I already have an account
              </button>
            </Link>
          </div>
        </form>
      </div>
    </div>
  );
};

// recipiece/apps/landing/src/app/pages/create-account/create-account.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'recipiece-create-account',
  templateUrl: './create-account.component.html',
  styleUrls: ['./create-account.component.scss']
})
export class CreateAccountComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="form-container">
  <div class="form">
    <h2>Create Account</h2>
    <fieldset>
      <label>
        Username
        <input [(ngModel)]="username" name="rcp-username" type="text" />
      </label>
      <label>
        Email
        <input [(ngModel)]="email" name="rcp-email" type="text" />
      </label>
      <label>
        Password
        <input [(ngModel)]="password" type="password" name="rcp-password" />
      </label>
      <label>
        Confirm Password
        <input [(ngModel)]="confirmPassword" type="password" name="rcp-password-confirm" />
      </label>
    </fieldset>
    <div class="button-container">
      <button (click)="stageUser()" class="button" type="button">Create Account</button>
    </div>
    <a class="button button-clear go-to-login-button" routerLink="../login">I already have an account</a>
  </div>
</div>
